import { Profile } from "@/types";

export const profilesData: Profile[] = [
  {
    username: "johndoe",
    name: "Carlos Salvino",
    bio: "Software Engineer",
    location: "San Francisco, CA",
    website: "https://carlossalvino.com",
    birthDate: "1990-01-01",
    joinedDate: "2021-01-01",
    profileImage: "/images/profiles/carlos.jpg",
    coverImage: "/images/covers/carlos.jpg",
    followers: 10,
    following: 10,
    tweetCount: 10,
    likes: 10,
    lists: 10,
  },
  {
    username: "john",
    name: "John Doe",
    bio: "Software Engineer",
    location: "San Francisco, CA",
    website: "https://johndoe.com",
    birthDate: "1990-01-01",
    joinedDate: "2021-01-01",
    profileImage: "/images/profiles/john.jpg",
    coverImage: "/images/covers/john.jpg",
    followers: 10,
    following: 10,
    tweetCount: 10,
    likes: 10,
    lists: 10,
  },
  {
    username: "jane",
    name: "Jane Doe",
    bio: "Software Engineer",
    location: "San Francisco, CA",
    website: "https://janedoe.com",
    birthDate: "1990-01-01",
    joinedDate: "2021-01-01",
    profileImage: "/images/profiles/jane.jpg",
    coverImage: "/images/covers/jane.jpg",
    followers: 10,
    following: 10,
    tweetCount: 10,
    likes: 10,
    lists: 10,
  },
];
