import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ClientLayout from "./clientLayout";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-black text-white")}>
        <div className="mx-auto w-full max-w-[425px] lg:max-w-[600px] xl:max-w-[800px] 2xl:max-w-[1000px] min-h-screen flex flex-col">
          <ClientLayout>{children}</ClientLayout>
        </div>
      </body>
    </html>
  );
}
